version: '3.4'

services:
  basketdb:
    image: redis:alpine
  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile 
  discountdb:
    image: postgres
  pgadmin:
    image: dpage/pgadmin4
volumes:
  postgres_data:
  pgadmin_data: